apiVersion: module-deployment.serverless.alipay.com/v1alpha1
kind: ModuleDeployment
metadata:
  labels:
    app.kubernetes.io/name: moduledeployment
    app.kubernetes.io/instance: moduledeployment-sample
    app.kubernetes.io/part-of: module-deployment
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: module-deployment
  name: moduledeployment-sample
spec:
  deploymentName: dynamic-stock-deployment
  template:
    spec:
      module:
        name: dynamic-provider
        version: '1.0.0'
        url: http://serverless-opensource.oss-cn-shanghai.aliyuncs.com/module-packages/stable/dynamic-provider-1.0.0-ark-biz.jar?Expires=1690825876&OSSAccessKeyId=TMP.3KkBner42hKhywrbHcxUSvaypwEqSV6P2nFhdxU6CFA3Z3FW9FNwWBLvBiNXMfwhLXEhSSiMLx6f25ynecTYD4fjVQXWys&Signature=hFVdNGqrzQ%2FnRsro6Cp8WMyjwpE%3D
  deployType: duideng
  replicas: 3
  strategy:
    upgradeType: installAndUninstall
    needConfirm: true
    useBeta: false
    batchCount: 3

