name: Arklet Unit Test
run-name: ${{ github.actor }} pushed arklet code

on:
  push:
    branches:
      - master
    paths:
      - 'arklet/**'
  pull_request:
    branches:
      - master
    paths:
      - 'arklet/**'
  # enable manually running the workflow
  workflow_dispatch:

env:
  WORK_DIR: arklet

defaults:
  run:
    working-directory: arklet

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache-dependency-path: ${{ env.WORK_DIR }}/go.sum

      - name: Run go mod
        run: go mod download

      - name: Build
        run: go build -a -o manager cmd/main.go

      - name: Test
        run: go test -v -json ./internal/controller > TestResults.json

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: ${{ env.WORK_DIR }}/TestResults.json
