name: CHAOSS Toolset GrimoireLab Deploy to Aliyun
run-name: ${{ github.actor }} manually deploy GrimoireLab to aliyun
 
on:
  workflow_dispatch:

env:
  WORK_DIR: project-management
  TAG: grimoire-lab-latest
  DOCKERHUB_REGISTRY: serverless-registry.cn-shanghai.cr.aliyuncs.com
  GRIMOIRE_LAB_IMAGE_PATH: opensource/stable/grimoire-lab
  POD_NAMESPACE: default
  
  
defaults:
  run:
    working-directory: project-management

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2.2.0
      with:
       registry: ${{ env.DOCKERHUB_REGISTRY }}
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
       logout: false

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push module-controller Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: ${{ env.WORK_DIR }}
        file: ${{ env.WORK_DIR }}/GrimoireLabDockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.GRIMOIRE_LAB_IMAGE_PATH }}:${{ env.TAG }}
