name: Module Controller Unit Test
run-name: ${{ github.actor }} pushed module-controller code
on:
  push:
    branches:
      - master
      - 'module-controller/**'
  pull_request:
    branches:
      - master
      - 'module-controller/**'
  # enable manually running the workflow
  workflow_dispatch:
env:
  CGO_ENABLED: 0
  GOOS: linux
defaults:
  run:
    working-directory: module-controller

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
          cache-dependency-path: go.sum
      - name: Install deps
        run: go mod download
      - name: Build
        run: go build -a -o manager cmd/main.go
      - name: Test
        run: go test -v -json internal/controller > TestResults.json
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: TestResults.json
        
