name: Module Controller Build and Deploy to Aliyun
run-name: ${{ github.actor }} pushed module-controller code

on:
  push:
    branches:
      - master
    paths:
      - 'module-controller/**'
  # enable manually running the workflow
  workflow_dispatch:

env:
  CGO_ENABLED: 0
  GOOS: linux
  WORK_DIR: module-controller
  TAG: ci-${{ github.sha }}
  
defaults:
  run:
    working-directory: module-controller

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker login
      uses: docker/login-action@v1.14.1
      with:
        registry: serverless-registry.cn-shanghai.cr.aliyuncs.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
        logout: false
        
    - name: Build the Docker image
      run: docker buildx build --file Dockerfile --platform linux/amd64 -t ${{ secrets.DOCKER_IMAGE_FULL_NAME }}:$TAG .
      
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_IMAGE_FULL_NAME }}:$TAG
      
    - name: kubectl-simple
      uses: steebchen/kubectl@v2.1.1
      with:
        config: ${{ secrets.CI_KUBE_CONFIG }}
        command: apply -f $WORK_DIR/config/samples/module-deployment-controller.yaml
