name: Module Controller Release
run-name: ${{ github.actor }} pushed module-controller code

on:
  create:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  CGO_ENABLED: 0
  GO_VERSION: 1.21.3
  GOOS: linux
  WORK_DIR: module-controller
  DOCKERHUB_REGISTRY: serverless-registry.cn-shanghai.cr.aliyuncs.com
  MODULE_CONTROLLER_IMAGE_PATH: release/module-controller

defaults:
  run:
    working-directory: module-controller

jobs:
  golangci-lint:
    name: "Go CI Linter"
    needs: [ style-check,resolve-modules ]
    runs-on: ubuntu-20.04
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Go Lint Test
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          working-directory: ${{ matrix.workdir }}
          args: "--out-${NO_FUTURE}format colored-line-number"




  build-push-linux-amd64-image:
    name: "Linux AMD64 Image"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKERHUB_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build and push module-controller Docker images
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v4.1.1
        with:
          context: ${{ env.WORK_DIR }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          file: ${{ env.WORK_DIR }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
          push: true
          tags: ${{ env.DOCKERHUB_REGISTRY }}/${{ env.MODULE_CONTROLLER_IMAGE_PATH }}:${{ steps.get_version.outputs.VERSION }}
